- app/src/androidTest/kotlin/com/wire/android/FunctionalTest.kt
- app/src/androidTest/kotlin/com/wire/android/InstrumentationTest.kt
- app/src/androidTest/kotlin/com/wire/android/MainActivityTest.kt
- app/src/androidTest/kotlin/com/wire/android/WireApplicationTest.kt
- buildSrc/src/main/kotlin/scripts/infrastructure.gradle.kts
This PR moves classes around (```androidTest```) in order to be consistent with the rest of the application package structure.
EXTRA BALL: Added extra information to its corresponding ```gradle``` task.
> Fix package structure for androidTest folder

- local.properties
local.properties file should not be pushed to remote repo because it contains environment specific settings.
> Remove local.properties file from remote repo - Part 1

- app/build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/core/android.gradle.kts
- buildSrc/src/main/kotlin/scripts/compilation.gradle.kts
This PR aims to clean up and refactor kotlin compile options to ```compilation.gradle.kts``` pre-compile Kotlin DSL gradle script. 
```kotlin
kotlinOptions {
jvmTarget = JavaVersion.VERSION_1_8.toString()
}
```
This fixes a tiny discussion from another PR:
https://github.com/wireapp/wire-android-reloaded/pull/11/files#r440705611
There are also some cosmetic extractions to ```Depedencies.kt```
> Refactor: move gradle kotlin compile options to compilation script.

- app/build.gradle.kts
- app/src/main/kotlin/com/wire/android/core/exception/Failure.kt
- app/src/main/kotlin/com/wire/android/core/functional/Either.kt
- app/src/main/kotlin/com/wire/android/core/usecase/UseCase.kt
- app/src/main/kotlin/com/wire/android/core/usecase/UseCaseExecutor.kt
- app/src/main/kotlin/com/wire/android/feature/auth/registration/di/RegistrationModule.kt
- app/src/main/kotlin/com/wire/android/feature/auth/registration/personal/CreatePersonalAccountFragment.kt
- app/src/main/kotlin/com/wire/android/feature/auth/registration/personal/email/CreatePersonalAccountEmailFragment.kt
- app/src/main/kotlin/com/wire/android/feature/auth/registration/personal/email/CreatePersonalAccountEmailViewModel.kt
- app/src/main/kotlin/com/wire/android/shared/user/email/ValidateEmailUseCase.kt
- app/src/test/kotlin/com/wire/android/MockitoKotlin.kt
- app/src/test/kotlin/com/wire/android/core/usecase/DefaultUseCaseExecutorTest.kt
- app/src/test/kotlin/com/wire/android/feature/auth/registration/personal/CreatePersonalAccountViewPagerAdapterTest.kt
- app/src/test/kotlin/com/wire/android/feature/auth/registration/personal/email/CreatePersonalAccountEmailViewModelTest.kt
- app/src/test/kotlin/com/wire/android/framework/livedata/Observers.kt
- app/src/test/kotlin/com/wire/android/shared/user/email/ValidateEmailUseCaseTest.kt
- app/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- buildSrc/src/main/kotlin/Dependencies.kt
Adds validation logic for email
Adds UseCase, Either, Failure
Bumps mockito version to 3.3.0 which has better support for coroutine testing
Fixes unit test assertions to conform to `assertThat(actual).isEqual(expected)` form.
> Registration #6: Add email validation logic

- app/src/androidTest/kotlin/com/wire/android/core/crypto/CryptoBoxClientIntegrationTest.kt
- app/src/main/kotlin/com/wire/android/core/crypto/CryptoBoxClient.kt
- app/src/main/kotlin/com/wire/android/core/crypto/data/CryptoBoxClientPropertyStorage.kt
- app/src/main/kotlin/com/wire/android/core/crypto/model/CryptoSessionId.kt
- app/src/main/kotlin/com/wire/android/core/di/Modules.kt
- app/src/main/kotlin/com/wire/android/core/events/Event.kt
- app/src/main/kotlin/com/wire/android/feature/conversation/content/EncryptedMessageEnvelope.kt
- app/src/main/kotlin/com/wire/android/feature/conversation/content/mapper/MessageMapper.kt
- app/src/test/kotlin/com/wire/android/core/crypto/CryptoBoxClientTest.kt
- app/src/test/kotlin/com/wire/android/feature/conversation/content/mapper/MessageMapperTest.kt
`CryptoBoxClient` is using `userId` (String), instead of the new `QualifiedId`. Better to fix this now than re-factor later in the future.
I changed the internals, replacing `userId: String` with `userId: QualifiedId`.
I've also identified some touching points (like when dealing with user-specific `SharedPreferences` and `MessageEvent`, for example) that remain using `userId`, but goes too far out of the scope of this PR.
It is currently impossible to make sure a session exists without calling the `assertSession`. And that requires a `PreKey`, something the sender may not have yet, and may not even need, if the session is already established.
I renamed `assertSession` to `createSessionIfNeeded` (@gizemb was right, the old name sucks).
I added a function `doesSessionExists` that enables us …
> CryptoBoxClient Update: QualifiedId and easier utilization without prekeys

- app/src/androidTest/kotlin/com/wire/android/core/crypto/CryptoBoxClientIntegrationTest.kt
Following a suggestion of @ohassine on #262
> refactor: improve naming of tests in `CryptoBoxClientIntegrationTest`

- app/src/main/kotlin/com/wire/android/core/network/ApiService.kt
- app/src/test/kotlin/com/wire/android/core/network/ApiServiceTest.kt
- app/src/test/kotlin/com/wire/android/feature/messaging/datasource/remote/MessageRemoteDataSourceTest.kt
1. The method `rawRequest` is currently very far from "raw", as it calls `performRequest` internally, handling all the HTTP errors and does not allow us to intercept the HTTP result at all.
It is only "raw" when the request succeeds, returning the response.
2. The `default` argument in the method `request` is too strong.
Maybe I just want a different `default` depending on the error `response`?
Change `performRequest` to do the bare minimal: check with `NetworkHandler` for connection and perform the request. Handle possible network exceptions.
Simplify `rawRequest` and add an option for it to take a different  `onResponseError` lambda, which allows us to intercept the request on error as well. By default, it goes with the default behaviour of analysing the HTTP Code and mapping to it to a …
> Refactor: Provide more control over network requests

- app/src/main/kotlin/com/wire/android/core/extension/OffsetDateTime.kt
- app/src/test/kotlin/com/wire/android/core/extension/OffsetDateTimeExtensionTest.kt
Since flying to Brazil some weeks ago, I've been having issues with one test that was asserting `UTC` Timezone and `US` Locale.
My system is currently at `BRT` timezone and the language is in German. So this test was **always** failing.
We should mock/set locale when testing this.
I've made sure all of our date formatting functions take the system locale into consideration and added a helping function that executes a block using a given Locale and returns it back to default when testing this.
Different JVM have different implementations of localization and date-time formatting.
For the same date and Locale:
On OpenJDK 8 : `20 de Julho de 2021 7h10min59s BRT`
On OpenJDK 11:   `20 de julho de 2021 07:10:59 BRT`
Ideally, I think we should have a home-coocked `DateTimeFormatter` that takes a …
> WIP: Consider Locale when formatting date and time

- app/build.gradle.kts
We are now displaying the version code in the version name so we can distinguish between different builds
> Chore: Display version code in version name

- app/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
forcing room to use the latest sqlite jdbc driver (for compatibility issues with m1 macs)
- This should be fixed in the upcoming room version 2.4.0
> fix: app build error on m1 macbook

- .github/workflows/semantic-commit-lint.yml
----
----
We want to ensure that PR titles should follow semantic commit rules
Add the semantic commit linter workflow from the Wire's .github repo
N/A
----
----
----
> ci: Add semantic commit lint of PR titles workflow SQPIT-769

- Jenkinsfile
- docker-agent/AndroidAgent
update the docker agent for wire android reloaded to use jdk11 container instead of jdk8
> ci: update docker agent file to use jdk11

- app/build.gradle.kts
- app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
- app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextFieldDefaults.kt
- app/src/main/res/drawable/ic_input_mandatory.xml
- buildSrc/src/main/kotlin/Dependencies.kt
- config/detekt/detekt.yml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-863" title="AR-863" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />AR-863</a>  Inputs
</td></table>
<br />
----
----
Material TextField has a min height bigger than we want (56dp) and the official "dense" version of it isn't yet available so we need a custom one which allows to set a lower height (40dp) and has a border width that matches the design.
----
----
----
> feat: add custom text field with proper styling [AR-863]

- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
----
----
JCenter is being just a big pain in the ass, going down all the time. It was supposed to be "read-only" for an undetermined amount of time, but it is very unreliable.
It turns out not only we still have it, but it had a higher order than Google's repo. 
Replaced JCenter with MavenCentral for the `buildSrc`, and just remove JCenter overall for the rest of the project.
If it build, it works. N/A
----
----
> chore: remove 💩Jcenter💩

- Jenkinsfile
- buildSrc/src/main/kotlin/scripts/variants.gradle.kts
----
----
When building APK's or App Bundles in our Jenkins machine, the artifacts are not signed.
Probably casing. Not 100% sure yet. The environment variable is defined as a boolean, and we are reading it and comparing with "TRUE".
Make it a bit more flexible
N/A?
----
> fix: signing not enabled when publishing builds

- Jenkinsfile
----
----
When publishing the app, we should fallback to `internal` as a safety measure. If we mistype anything in the script and we can't figure out the correct track, it shouldn't publish the app to production.
`defineTrackName()` in Jenkinsfile was returning `production` by default.
Now it returns `internal` by default
N/A
----
----
> chore: make `internal` the default track for publishing

- build.gradle.kts
----
----
the project is not building with the following error
```kotlin
Could not determine the dependencies of task ':app:processDevDebugResources'.
> Could not resolve all task dependencies for configuration ':app:devDebugRuntimeClasspath'.
> Could not find app.cash.sqldelight:android-driver:2.0.0-SNAPSHOT.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/app/cash/sqldelight/android-driver/2.0.0-SNAPSHOT/maven-metadata.xml
- https://dl.google.com/dl/android/maven2/app/cash/sqldelight/android-driver/2.0.0-SNAPSHOT/android-driver-2.0.0-SNAPSHOT.pom
- https://repo.maven.apache.org/maven2/app/cash/sqldelight/android-driver/2.0.0-SNAPSHOT/maven-metadata.xml
- …
```
> fix: missing sonatype repo

- app/build.gradle.kts
- app/src/main/kotlin/com/wire/android/di/AppModule.kt
- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/Auth.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
----
----
the login flow is changed in kalium, and playtest was not possible because of missing classes while building with minify,
this PR 
refactor `loginViewModel` and `LoginScreen` to pass `serverConfig` (for now it's only staging) and disable the login flow until the minify issue is solved
----
> chore: refactor login with the new flow

- app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1100" title="AR-1100" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />AR-1100</a>  Invalid Email inline error message should disappear as user types or change email text
</td></table>
<br />
----
----
[AR-1100]
clear the login error state after input change
manually 
----
----
----
[AR-1100]: https://wearezeta.atlassian.net/browse/AR-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
> fix: updating login screen error state [AR-1100]

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-912" title="AR-912" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />AR-912</a>  Send text messages
</td></table>
<br />
----
----
> Sometimes you just gotta lick the stamp and send it 👅📮
We need the UseCase to be defined and accessible to the ViewModel in order to send messages.
Add `SendTextMessageUseCase` to `ConversationViewModel` in order to enable sending of messages.
N/A
Integrating the usecase with the input will be handled in another PR.
----
----
1. E.g. …
> chore: add SendTextMessageUseCase to ConversationViewModel (AR-912)

- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
- app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-912" title="AR-912" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />AR-912</a>  Send text messages
</td></table>
<br />
----
----
- When a user taps on send message button, that message gotta be sent.
- ViewModel is not able to update the state to clear the input after sending the message
- Small rework on `MessageComposer` in order to control the text input from the view model state (thanks @trOnk12)
- Call the right UseCase when the user interacts with the button
Manually tested
----
----
1. …
> feat: send message (AR-912)

- app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileScreen.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1139" title="AR-1139" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />AR-1139</a>  Self profile displays incorrectly on Pixel3
</td></table>
<br />
----
----
Issue:
The CurrentUserStatus was not correctly centered.
Solution:
Center the Row 
----
----
----
> fix: center the currentuserstatus (AR-1139)

- app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileViewModel.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1139" title="AR-1139" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />AR-1139</a>  Self profile displays incorrectly on Pixel3
</td></table>
<br />
----
----
Adds a couple of mocked teams on the User Profile
----
----
----
> fix: show mocked data for Other Teams section on User Profile [AR-1139]

- app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileViewModel.kt
----
----
Add a missing navigation case to under construction, for the button  on user profile to create a new account or team
----
----
----
> fix: add missing navigation to create account under construction for user profile 

- app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountNavigationItem.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountScreen.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/OverviewScreen.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeViewModel.kt
- app/src/main/res/drawable/ic_create_personal_account.xml
- app/src/main/res/values/strings.xml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-954" title="AR-954" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />AR-954</a>  navigate from welcome screen to register
</td></table>
<br />
----
----
User needs to be able to create a personal account. The creation flow has to be open by pressing the "Create a private account for free" on WelcomeScreen.
- implemented "Overview" screen (first one in personal account creation flow)
- refactored "Auth" nested navigation
- implemented "Create personal account" nested navigation
https://user-images.githubusercontent.com/30429749/155524779-a5381702-dda4-4abf-9228-55605462ba0b.mp4
---- …
> feat: "create personal account" - "overview" screen and navigation [AR-954]

- app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountNavigationItem.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewState.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/EmailScreen.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/OverviewScreen.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/PersonalDetailsScreen.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDevice.kt
- app/src/main/kotlin/com/wire/android/ui/common/Extensions.kt
- app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
- app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
- app/src/main/kotlin/com/wire/android/ui/theme/WireTypography.kt
- app/src/main/kotlin/com/wire/android/ui/theme/WireTypographyBase.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileViewModel.kt
- app/src/main/res/values/strings.xml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1069" title="AR-1069" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />AR-1069</a>  implement the registration personal flow UI
</td></table>
<br />
----
----
User needs to be able to fill out a personal account creation flow.
- implemented "enter email" screen UI with error handling
- implemented "enter details" screen UI with error handling
https://user-images.githubusercontent.com/30429749/156128296-cc3a1d43-e29d-4dfd-b879-d6eebc8d5046.mp4
----
----
---- …
> feat: "create personal account" - "email" and "details" UI [AR-1069]

- .github/workflows/gradle-run-tests.yml
- app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileViewModel.kt
----
----
When name or handle are not set, the app crashes.
Coalesce to empty string `name` and `handle`
Register an account on web and close the application before setting a username.
Login into the app. The app doesn't crash when accessing the profile screen.
----
----
> fix: coalesce to empty string name & handle in profile

- buildSrc/build.gradle.kts
----
----
Due to updating android tools build from `7.0.3` to `7.0.4` in Kalium, when running latest develop in Kalium and AR project it wouldn't build and would ask to bump the version.
Bumped android tools build gradle versiom from `7.0.3` to `7.0.4` to match Kalium when running latest develop
----
> chore: update android tools build gradle to 7.0.4 to match kalium

- app/build.gradle.kts
----
----
Gradle complaining about 2 google protobuf versions
having 2 google protobuf versions
Pick one for Gradle because computers are indecisive creatures
> fix: Gradle complaining about 2 google protobuf versions

- app/src/main/kotlin/com/wire/android/di/ClientScopeProvider.kt
- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
----
----
after the kalium changes in [refactor: replace nonQualifiedID with qualifiedID #335 ](https://github.com/wireapp/kalium/pull/335) `getSessionScope` takes UserId 
replace the nonQualifiedID with qualifiedID
----
----
> fix: inject qualifiedID

- Jenkinsfile
----
----
Jenkins can be a bit overloaded when we have too many recent builds ordered.
At the moment we can have up to 4 jobs running in Jenkins.
Each commit already triggers two builds on our Jenkins runners:
One that checks the branch integrity by itself without any relationship to any PR, and another one that checks if the PR is good to merge against the target branch.
If we send a couple of commits to one branch, Jenkins gets overloaded and new builds are queued up for the future. (See attachments)
Initialy. Abort ongoing builds of the same branch/PR when a new commit is made.
Two runs on this PR to see what gives :)
If it works, it works.
We could see about disabling builds for branches (other than `main`, of course). And only building PRs. …
> ci(jenkins): abort ongoing runs upon new commits

- app/build.gradle.kts
- app/src/main/kotlin/com/wire/android/datastore/UserDataStore.kt
----
----
This new config, address the error from develop caused by multiple datastores. I added a configuration to clear the state of the app before running tests. Also, as suggested by the error, moved the datastore to the companion object for uniqueness 
```
Starting 14 tests on Android SDK built for x86_64 - 9
com.wire.android.ui.ConversationScreenTest > userSearchesConversation[Android SDK built for x86_64 - 9] SKIPPED 
Starting 14 tests on Android SDK built for x86 - 10
com.wire.android.ui.ConversationScreenTest > userSearchesConversation[Android SDK built for x86 - 10] SKIPPED 
com.wire.android.ui.LoginScreenTest > login_success_case[Android SDK built for x86_64 - 9] FAILED 
java.lang.AssertionError: Failed to perform isDisplayed check. …
```
> fix: ui tests isolation and datastore management

- .github/workflows/gradle-run-ui-tests.yml
- Jenkinsfile
----
----
* CI is failing to start UI tests.
* UI tests are unstable. We should stop running them on Jenkins temporarily as they aren't solid yet.
* Malformed YML file when getting the `api-level` from the matrix value.
`$` for the YML.
Replace `connectedCheck` with `runAcceptanceTests`, which is a home-made task that we can customise deeper if we want to. Also, runs tests only once instead of once per flavour.
`ui-tests` job should run successfully on this PR.
Jenkins should not run `runAcceptanceTests`.
----
----
> ci: fix UI tests job and disable them on Jenkins

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1178" title="AR-1178" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />AR-1178</a>  Display user metadata in conversation view
</td></table>
<br />
----
----
Correctly display the conversation title in the `ConversationScreen`.
Use the new `ObserveConversationDetailsUseCase` from Kalium.
Just open any (real) conversation from the conversation list.
Where it says "Gonzalo" it used to say "Some Name":
----
----
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title …
> feat(conversation): display 1:1 conversation title (AR-1178)

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationMemberExt.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1179" title="AR-1179" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />AR-1179</a>  User display name
</td></table>
<br />
----
----
Display the message sender's name instead of the hard-coded `"Cool User"`.
Use the new `ObserveConversationMembersUseCase` from Kalium and combine this flow with the messages flow when mapping to UI state.
Just send/receive messages!
----
----
> feat(conversation): display message sender name (AR-1179)

- Jenkinsfile
----
----
The build jobs sends messages into the build chat on success which contain code tags ```. The chat is very slow to open. 
Every time when opening this chat with the webapp/desktop app the syntax highlighter tries to parse and guess which language the code has.
With the term `text` we disable the highlighting.
----
----
----
> chore: No syntax highlighting in build messages for performance (SQPIT-926)

- app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
- app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/HomeState.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-994" title="AR-994" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />AR-994</a>  Increase navigation drawer closing area
</td></table>
<br />
----
----
The Design team requires, by its specs, that the `NavigationDrawer` have a scrim size of 56.dp. This is not possible using the latest compose material lib, see more at: https://issuetracker.google.com/issues/207957335
As this is a spec expected from design team (having a minimum scrim margin of 56.dp) I change the `NavigationDrawer` to a `ModalDrawer` that has this margin by default. 
**Material 3 component lib :**
**Material component …
> fix: drawer scrim size accordingly to design specs (AR-994)

- app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/SearchListNavigationHost.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/Screen.kt
----
----
after adding the new group name screen the search flow was not working properly
update the navigation flow by using nested navhosts
go to the new conversation flow and try to search 
----
----
----
> fix: new conversation search fix

- app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
- app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
- app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
----
----
_adjust message items paddings
----
----
----
> fix: adjust message item paddings

- app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDevice.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceState.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
----
----
The keyboard behaviour on "remove device" screen and its dialog was still wrong - the previous fix that prevented keyboard from opening when the password was pasted actually made the keyboard hide when it shouldn't, for instance during entering the characters.
Changed the name of the state field to `hideKeyboard` to only be used when it should really hide the keyboard and text field focus should be requested once when the dialog is shown, thus `LaunchedEffect` is used.
Login having too many devices registered to trigger the "remove device" screen and then try to enter or paste the password when removing any device.
----
----
1. E.g. …
> fix: remove device keyboard behavior

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
----
----
- the use case was renamed on the Kalium
- the use case does not return Flow any more
- use correct name
- consume the list instead of flow
----
----
----
> fix: rename the get all contacts use case

- app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallScreen.kt
- app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/CallOptionsControls.kt
- app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/CameraButton.kt
- app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
----
----
[AR-1260 - request camera permission](https://wearezeta.atlassian.net/browse/AR-1260)
When receiving an incoming call or on an ongoing call, and the user hasn't given permission to access the camera, when clicking on camera button nothing would happen.
Ask for user permission to use its camera when receiving an incoming call or on an ongoing call.
- Open the app
- send a message to the caller
- receive an incoming call
- tap on the camera button
- permission prompt should pop up
> feat: add request camera permission in calling

- app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmail.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSO.kt
- app/src/test/kotlin/com/wire/android/ui/authentication/LoginViewModelTest.kt
…ogin
----
----
Fixed assigning correct value for server config in login tabs and set the staging as default sso login
The custom server config loaded from the deeplink wasn't assigned correctly to the next pages.
After refactoring, a place to set the value was missed! also added some new tests.
Added tests and fixed the value passing in other pages.
added unit tests for the function.
SSO login should work with staging directly.
Deeplinks has another server config that should change the app server config correctly.
----
----
----
> fix(sso-login): loading server config from deep link and set staging for SSO login

- app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/ModalSheetHeaderItem.kt
- app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetLayout.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MutingOptionsSheetContent.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerViewModel.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1413" title="AR-1413" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1413</a>  Update profile picture by Gallery - tapping confirm button fastly many times crashes the app
</td></table>
<br />
----
----
This PR fixes 2 unrelated issues:
1. User avatar picture uploading crash, when hitting desperately the confirm button, we added an uploading state to block the button
2. Adjust padding for header in muting options bottom sheet
----
----
----
1. E.g. `feat(conversation-list): Sort …
> fix: profile pic issue and muting options ui adjustment (AR-1413) (AR-1043)

- app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmail.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSO.kt
----
----
Changed the location of server title in each login tab, to see which server we are pointing to
In login page and in login with email and login with sso tabs, the input label has the pointing server title in it.
----
----
----
> chore(login): change the location of server title in login page

- app/src/main/kotlin/com/wire/android/ui/common/BottomNavigation.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
- app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1474" title="AR-1474" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1474</a>  Conversations - Some groups appear on list only after restarting the app
</td></table>
<br />
----
----
Detected suspicious missing conversations every time we open the app!
After some logging and checking, I found a spooky hidden thing! The lost conversation was below the bottomNavigation!
)
Added the height of the navigationBottom to the NavHost to the main screen.
Manual testing
----
----
----
1. …
> fix: add bottomNavigation height as padding to the main home navHost [AR-1474]

- app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
----
----
App crash when receiving notification for unauthenticated account
the notification should be handled if and only if the user is authenticated.
----
----
----
> fix: app crash when receiving notification for unauthenticated account

- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
- app/src/main/kotlin/com/wire/android/util/FileUtil.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1663" title="AR-1663" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1663</a>  Scrolling in the conversation is not smooth and images are flickering
</td></table>
<br />
----
----
While typing a message the ConversationScreen were recomposed causing images and other items being recomposed.
The lambda was recreated invalidating the items
pass a function reference instead of a lambda
1. Open a conversation with image assets
2. Start typing
The image should no longer flicker.
I found not really intuitive issue causing the Image Assets being recomposed inside the ConversationScreen:
If we …
> fix: pass an function reference instead of a lambda [AR-1663]

- app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/gallery/ZoomableImage.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1149" title="AR-1149" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />AR-1149</a>  Create Detailed Image Preview screen 
</td></table>
<br />
----
----
According to AR-1149 design feedback, the detailed image screen had some issues such:
- Image shouldn't be able to zoom out
- Title of the screen should be the name of the other user for 1:1 screens
This PR fixes those.
----
----
----
> fix: issues with MediaGalleryScreen [AR-1149]

- app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachment/AttachmentOptions.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1469" title="AR-1469" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1469</a>  Video is sent when tapping back button
</td></table>
<br />
----
----
Video or picture files were being sent even if the user didn't confirm the video/photo taken and navigated back. This was caused because we were not checking the boolean flag `hasCapturedVideo/hasTakenPicture` when passing through the file uri to the requestFlow. Now we will only send these files if this flag is set to `true`
Open a conversation, click on take video or picture, when on the camera screen, click back button on the device. …
> fix: don't send video when clicking navigation back from camera app [AR-1469]

- app/src/main/kotlin/com/wire/android/di/AppModule.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/DownloadedAssetDialog.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageViewWrapper.kt
- app/src/main/kotlin/com/wire/android/util/FileManager.kt
- app/src/main/res/drawable/ic_download.xml
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1323" title="AR-1323" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />AR-1323</a>  Process a file after it has been downloaded
</td></table>
<br />
----
----
The Design team decided to have [an alternative flow](https://www.figma.com/file/UgKehvwIbiIiQ2CCEdsVuf/Android?node-id=15741%3A130748) where asset messages would have several download states (internal and external). This PR just accommodates this new flow with the recently merged [PR on kalium](https://github.com/wireapp/kalium/pull/526)
Just send and receive asset messages!
----
----
----
1. …
> fix: implement new asset download flow [AR-1323]

- app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/AppTopBarWithSearchBarLayout.kt
- app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/SearchBarState.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/SearchPeopleRouter.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleScreen.kt
----
----
- When pressing the back button the search result was not cleared 
- When navigate to other user profile screen, the search results were cleared, due to not having rememberSaveable for the search state.
----
----
----
> fix: clear the search on back press

- app/src/main/kotlin/com/wire/android/mapper/UserTypeMapper.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
- app/src/test/kotlin/com/wire/android/mapper/UserTypeMapperTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
----
----
- Kalium exposes now a user type on conversation details, which we can map now into the ui 
----
----
----
> feat: map the user type to the ui on conversation

- app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/AcceptButton.kt
- app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/CameraButton.kt
- app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/CameraFlipButton.kt
- app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/DeclineButton.kt
- app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/MicrophoneButton.kt
- app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/SpeakerButton.kt
----
----
Due to upgrading Material version to v3, icons dimensions were changed (due to not having both width/height specified)
Add both width AND height to calling icons
| OLD Design | New Design |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/5890660/170263522-f0749693-bd5a-4a10-a988-767518a0aea0.jpeg" alt="old_init" width="300" height="400" />  | <img src="https://user-images.githubusercontent.com/5890660/170263670-26925e28-32cc-40e3-b74d-54134169397e.jpeg" alt="new_init" width="300" height="400" />  |
| <img src="https://user-images.githubusercontent.com/5890660/170263753-dd345e51-d2fc-4f39-9db7-c72c6af63f16.jpeg" alt="old_incoming" width="300" height="400" />  | <img …
> chore: adjust calling button dimensions

- app/src/main/kotlin/com/wire/android/media/CallRinger.kt
----
----
[AR-1386 - Reject group call](https://wearezeta.atlassian.net/browse/AR-1386)
When rejecting a call, ringer should stop ringing, but it also crashed the app or the screen was not dismissed.
The exception that was being thrown:
`java.lang.IllegalStateException at android.media.MediaPlayer.isPlaying(Native Method)`
Add proper handling of mediaPlayer if null or not null to handle the ringing stop.
> chore: add proper handling of media player to stop it ringing

- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
----
----
Mute options per conversations are respected
Check the mute options and fake mentions by checking if the text of the message contains either the user's display name or it's handle
Use the Echo bot that mentions you when it echoes back a message
----
----
> feat: respect mute options per conversation

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1809" title="AR-1809" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1809</a>  When removing member from the group conversation, entering it, crashes the app
</td></table>
<br />
----
----
Crash when opening a group which contains messages from users who have already been removed from it.
Used new use case that allows us to observe not only current conversation members but all the current and past users from the conversation that are needed in order to show messages properly.
Remove a user that wrote a message from group and try to open this group.
----
----
----
1. …
> fix: crash when displaying message from user removed from group [AR-1809]

- app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
Made message's text color depends on device's dark/light mode, so it will be visible in both.
> fix: Message textColor for dark mode

- app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/usecase/GetMessagesForConversationUseCase.kt
- app/src/main/kotlin/com/wire/android/util/ui/UIText.kt
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
- app/src/test/kotlin/com/wire/android/mapper/MessageContentMapperTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/GetMessageForConversationsUseCaseTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1827" title="AR-1827" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1827</a>  All message types are stored and visible on conversation screen
</td></table>
<br />
----
----
Currently all message types, even ones not yet handled by app, are stored in DB as "Unknown" and visible with "content is not available".
"HIDDEN" messages aren't displayed at all, "Unknown" types have more meaningful texts, updated kalium reference and names of types adjusted to reflect changes in kalium.
Just open conversation and check what messages are displayed.
----
----
----
1. …
> fix: ignore or hide some message types [AR-1827]

- .github/workflows/create-playtest-branch.yml
----
----
Internal playtest are a bit messy at times since we wait till the last moment to cut from a build from the `main` branch. 
Add a workflow to manually or automatically create a branch starting with `playtest/` for playtest purposes. Triggered automatically every Thursday morning or manually at will.
----
----
> ci: add playtest branch workflow

- app/src/test/kotlin/com/wire/android/navigation/NavigationUtilsTest.kt
----
----
A change on `parseIntoQualifiedID` broke a test.
Adjust test to comply with changed `parseIntoQualifiedID` as it doesn't return an exception anymore.
> fix: adjust test to comply with function not returning an exception

- app/src/main/kotlin/com/wire/android/ui/authentication/create/common/CreateAccountBaseViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreateAccountOverviewScreen.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreateAccountOverviewViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/team/CreateTeamViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
----
----
1. app crashing when opening screen.
2. forgot password, tos and pricing url are not working 
1. in `CreateAccountViewModel` `RegisterPushToken` was injected in the constructor which is a user session use case, when injecting such usecases in viewmodels before the account is authenticated the app crash because there is no session for the user.
2. changes to the `ServerConfig` class in kalium can brake how the links should be created.
3. the path was added to the end of the url string with out any consecration to correct url building.
_Specify here any other facts that you think are important …
> fix: app crash on create new account screen and broken links

- app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
- app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationMemberExt.kt
----
----
Right now, we get old system messages and it can create the situation where we need data of user that was removed even before we started using the app so we don't have any data about that user stored in DB.
Check if user details are available from the DB, if not then replace the name with a generic "Deleted User".
----
----
> fix: member removed not stored in DB is blocking the flow

- app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
- app/src/main/kotlin/com/wire/android/util/DateTimeUtil.kt
- app/src/test/kotlin/com/wire/android/mapper/MessageMapperTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1420" title="AR-1420" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />AR-1420</a>  Timestamp 
</td></table>
<br />
----
----
Messages didn't display timestamps
Display timestamps according to:
```
when timestamp.isToday 
true -> timestamp.justTheTime
false -> timestamp.timeAndDate
```
----
----
----
> feat: add timestamps to messages AR-1420

- app/src/main/kotlin/com/wire/android/navigation/NavigationManager.kt
- app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
- app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
- app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModel.kt
- change handling `NavigationManager.navigateBack()`
- added new `BackStackMode.REMOVE_CURRENT` it removes the current item from the navigation backStack before navigating to the new one.
In cases when `NavController.popBackStack()` is called and the current screen is the only item in backStack, then empty screen is displayed. 
That issue could appear when the app was opened by `PendingIntent` from the notification and `NavController.popBackStack()` is called (NOT android back button).
Example scenario: 
- kill the app on device1
- call from device2 to device1
- device1 shows IncomingCallScreen (it's not yet implemented but will be soon :) )
- cancel a call on device2, or decline a call on device1
As a result: 
empty screen is displayed (kinda default compose-navigation screen, before …
> chore: Back Navigation improve

- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/SnackbarMessages.kt
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1271" title="AR-1271" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />AR-1271</a>  Toast for deletion error
</td></table>
<br />
----
----
There's no feedback to the user when there's a failure when deleting messages.
Handle the error and display a snackbar.
1. Turn off your internet connection;
2. Attempt to delete a message.
https://user-images.githubusercontent.com/9389043/174299377-009a6b83-1db1-4cb8-968b-a301697e62eb.mov
----
----
1. E.g. `feat(conversation-list): Sort …
> feat: display error when failing to delete message (AR-1271)

- app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
- app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
- app/src/test/kotlin/com/wire/android/mapper/MessageContentMapperTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1143" title="AR-1143" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />AR-1143</a>   Conversation setting messages (system) 
</td></table>
<br />
----
----
System messages still needed some polishing in order to pass the design review. There were some [comments](https://wearezeta.atlassian.net/browse/AR-1143?focusedCommentId=102200) from Wolfgang needed to be addressed.
----
----
> fix: system messages design review changes [AR-1143]

- app/src/main/kotlin/com/wire/android/mapper/AssetsUtil.kt
- app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
- app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
- app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
- app/src/test/kotlin/com/wire/android/mapper/MessageContentMapperTest.kt
----
----
Sharing SVG files as images was causing some app crashes. Because even though their mime type is "image/svg", our app can't interpret this format in order to render it inlined in the chat.
To add a utils method to whitelist only "jpeg", "jpg" and "png" as _valid_ image types. If we plan on support or display other image types, we will need to add this mime type to the list.
Just share an svg file as image !
https://user-images.githubusercontent.com/2468164/174822903-fb01c145-cb37-4703-ab77-2e1f77632460.mov
----
----
----
> fix: fixed crash when sending/receiving svg images

- app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/HighLightName.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/HighLightSubtTitle.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1867" title="AR-1867" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1867</a>  Long name doesn't fit on New Conv. List Screen
</td></table>
<br />
----
----
Long names in search extend passed 1 line, stretching the visuals vertically
Limit the text to 1 line and truncate the rest
Manual
Search for me or @dogaguclu 
----
----
----
> fix: truncate long names in search AR-1867

- app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
- app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
- app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
- app/src/test/kotlin/com/wire/android/mapper/MessageContentMapperTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1685" title="AR-1685" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1685</a>  When receiving an image as attachment from web, android does not show the file
</td></table>
<br />
----
----
Images received from web client shared as files come with their asset metadata `width` and `height` set to 0. This was causing the image not to render at all.
If an image message comes with any of these metadata values set to 0, we will treat it as a Generic Asset Message instead.
_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as …
> fix: displayed received images with null width and height as asset messages [AR-1685]

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
- app/src/main/kotlin/com/wire/android/ui/common/WireLinearProgressIndicator.kt
- app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
- app/src/main/kotlin/com/wire/android/ui/home/sync/SyncStateViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/sync/SyncViewState.kt
----
----
Users have no way to know what is going on with the app, if the connection is established or not.
It also sucks for us, because it gets harder to understand what is going on without getting logs.
Add a progress indication on the HomeView to display SyncState
- Nothing: Live or Waiting
- 🔵 Slow Sync
- 🟢 Quick Sync / Pending Events
- 🟡 No internet connection
- 🔴 Unknown failure
As this was done mainly with debugging in mind and as a placeholder for an actual designed feature, I've only tested it manually.
Log in and open the main screen.
https://user-images.githubusercontent.com/9389043/175065826-66d350a8-c60b-41af-b780-cb7de6d1c608.mp4
----
----
1. …
> feat: dysplay sync status on the home screen

- app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
- app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
- app/src/main/kotlin/com/wire/android/navigation/SavedStateViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
- app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
----
----
There is an issue with navigating back with arguments, passing such arguments to the ViewModel and clearing them when not needed anymore.
Created SavedStateViewModel - ViewModel which already has SavedStateHandle parameter by default. Implemented hiltSavedStateViewModel method which takes NavBackStackEntry as an argument to pass the arguments to the ViewModel's SavedStateHandle. Every navigation (back and forward) updates the back navigation arguments of the current or previous entry. Added external functions for easier getting navigation arguments from SavedStateHandle.
Currently it's used in two situations:
- removing image from media gallery screen, it should remove message after going back to conversation screen
- ignoring …
> fix: back navigation with arguments

- app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1865" title="AR-1865" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1865</a>  Images are flickering while typing message on a conversation
</td></table>
<br />
----
----
The images inside the MessageComposer were recomposed.
-Once again our well beloved Lambda creation.
- remember the Clickable object so that it does not get recreated.
_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as …
> fix: remember the Clickable so that we do not Recompose the image content (AR-1865)

- app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1837" title="AR-1837" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1837</a>  Loading indicator for SSO login
</td></table>
<br />
----
----
[AR-1837]
Enabled loading indicator on login button when the sso login is in progress.
Manual test: do an sso login, after getting back from the OKTA page, the login button should be set disabled and in loading state.
----
----
----
1. …
> fix(sso-login): add loading indicator to SSO login page (AR-1837)

- app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
----
----
The ongoing call screen is not visible when device is locked
Keep screen alive by changing screenMode to `WAKE_UP` 
Make a call and wait for some moments until your device is locked
----
----
----
> feat(calling): keep ongoing call screen awake

- app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1725" title="AR-1725" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1725</a>  Pressing back button on sharing files section closes the conversation instead
</td></table>
<br />
…d close options instead of whole screen
----
----
on conversation screen when user opens share file options and press system navigation back button, we should close the options instead of whole conversation
changing behavior when system button is clicked
_If …
> fix: (AR-1725) Pressing back button on sharing files section closes the conversation instead

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/mapper/ContactMapper.kt
- app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
- app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
- app/src/main/kotlin/com/wire/android/mapper/UIParticipantMapper.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationMemberExt.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/usecase/ObserveParticipantsForConversationUseCase.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/usecase/GetMessagesForConversationUseCase.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
- app/src/test/kotlin/com/wire/android/framework/TestUser.kt
- app/src/test/kotlin/com/wire/android/mapper/MessageContentMapperTest.kt
- app/src/test/kotlin/com/wire/android/mapper/UIParticipantMapperTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/GetMessageForConversationsUseCaseTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/details/participants/usecase/ObserveParticipantsForConversationUseCaseTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
- app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1041" title="AR-1041" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />AR-1041</a>  Group Admins
</td></table>
<br />
----
----
[AR-1041]
expose the member role from the Kalium and show the new info on the conversation member screen
----
----
----
[AR-1041]: https://wearezeta.atlassian.net/browse/AR-1041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
> feat: group members roles [AR-1041]

- app/src/main/kotlin/com/wire/android/ui/common/LinkifyText.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1992" title="AR-1992" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1992</a>  Long Tap on text messages doesn't bring up message option menu (i.e. delete, copy...)
</td></table>
<br />
----
----
- text in message didn't respond for long clicks 
- pass long click event from text 
_Specify here any other facts that you think are …
> fix: long tap on message (AR-1992)

- app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/JoinButton.kt
----
----
[AR-1053](https://wearezeta.atlassian.net/browse/AR-1053)
Design was a bit off for the Join Call Button
Adjust the button padding so it looks more like in design.
| OLD BUTTON  | NEW BUTTON |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/5890660/180241225-cc10cbd9-41ac-45d5-b858-8dd775249fd1.png" width="300" height="140" /> | <img src="https://user-images.githubusercontent.com/5890660/180241410-ba148f2c-4640-45e5-a576-9fcb2a0c9972.png" width="300" height="140" /> |
> chore: adjust join button padding

- app/src/androidTest/java/com/wire/android/di/TestModule.kt
- app/src/androidTest/java/com/wire/android/utils/Extensions.kt
----
----
Attempt to be able to "retry" for limit logins on staging accounts (workaround)
----
----
----
> chore: add retry automation login when session is blocked on staging accounts

- app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerViewModel.kt
- app/src/main/kotlin/com/wire/android/util/AvatarImageManager.kt
- app/src/main/kotlin/com/wire/android/util/FileUtil.kt
- app/src/test/kotlin/com/wire/android/ui/userprofile/image/AvatarPickerViewModelTest.kt
----
----
After assets refactoring, image messages were not being resampled. 
I refactored a bit the flow for resampling avatars (small size) and asset messages (medium size) so that they use the same new util method called `Uri.resampleImageAndCopyToTempPath()`
Update your avatar image with a new large image and check the final one uploaded is way smaller. Same with images in conversations.
----
> fix: refactored way to resample avatar and images assets

- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
----
----
onClickListener was not recreated with a state of Conversation changed , so when we muted the conversation it was not reflected in the UI
----
----
----
> fix: pass conversation to onConversationItemClick callback

- app/src/main/kotlin/com/wire/android/WireApplication.kt
- app/src/main/kotlin/com/wire/android/mapper/ContactMapper.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/common/UsernameMapper.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2036" title="AR-2036" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2036</a>  No domain is displayed in search result for users from another backend
</td></table>
<br />
----
----
This PR enables showing information about the domain for federated users
----
----
----
> fix: map username/label for federated users (AR-2036)

- Jenkinsfile
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-1128" title="SQPIT-1128" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />SQPIT-1128</a>  Develop builds should be in a separate folder then PR builds on megazord for Android Reloaded Project
</td></table>
<br />
----
----
The Jenkins configuration for `wire-android-reloaded` uploads *all* CI builds to the same path in S3, which makes it difficult to determine which branch a given build corresponds to. This makes it harder for QA to find the latest `develop` build in order to test for regressions.
This change adds a second upload step to the CI configuration so that builds on `develop` …
> feat: upload develop builds to separate S3 path from CI [SQPIT-1128]

- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2041" title="AR-2041" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />AR-2041</a>  (ui) Navigation from conversation detail delete
</td></table>
<br />
----
----
Given that we receive a conversation deleted event, we need to react (remove it from the conversations list) and if we are on the details view, we need to navigate back to the conversations lists, because this conversation is not available anymore.
https://user-images.githubusercontent.com/5806454/182393652-66ca6967-81ff-4d20-a7bc-ec18a7b42a1a.mov
----
----
----
1. …
> feat: delete conversations events navigation to home on deleted (AR-2041)

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
----
----
Our new `QualifiedIdMapper` injected from hilt requires session as it's from `UserSessionScope` and uses `UserRepository` and it crashes the login screen.
Add new `@NoSession` annotation and add second `QualifiedIdMapper` provider to the `CoreLogicModule`, the one that doesn't require session and inject it with this annotation into `LoginViewModel`.
----
> fix: login session crash (QualifiedIdMapper)

- app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceViewModel.kt
- app/src/test/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2029" title="AR-2029" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2029</a>  At login, I can't remove the additional devices
</td></table>
<br />
----
----
AR-2029
unnecessary password validation
remove any password validation when the user enter their passwords 
----
----
----
1. …
> fix: some Users can't register new client on RegisterDeviceScreen [AR-2029]

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/CallNotificationDismissReceiver.kt
- app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/ConnectionRequestNotificationDismissReceiver.kt
- app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/MessageNotificationDismissReceiver.kt
- app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/NotificationReplyReceiver.kt
- app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/SummaryNotificationDismissReceiver.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
- app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
- app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
- app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2137" title="AR-2137" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2137</a>  App is crashing when tapping on "New Conversation" Button
</td></table>
<br />
----
----
QualifiedIdMapper is only provided in a ViewModel scope and requires user session. It's wrongly injected into BroadcastReceivers - they must have zero arguments constructor to work so everything needs to be injected as `lateinit var`. 
Provided another QualifiedIdMapper with @NoSession annotation in a SingletonComponent and injected with this annotation into @AndroidEntryPoint BroadcastReceivers (they doesn't have its …
> fix: QualifiedIdMapper crashes [AR-2137]

- app/src/main/kotlin/com/wire/android/ui/common/WireSwitch.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1884" title="AR-1884" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />AR-1884</a>  Separate guests and services + make admin control them
</td></table>
<br />
----
----
conversation options screen doesn't match design
change padding to match design and use scale to make the switch a bit smaller
----
----
----
> fix: UI fix [AR-1884]

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/create/common/CreateAccountBaseViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceState.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
- app/src/test/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModelTest.kt
----
----
AR-1999
1. store the user SSOID from the user info response
2. user `IsPasswordRequiredUseCase` to know when to ask the user to enter their password.
----
----
----
> fix: handle user SAML settings when registering account

- app/src/main/kotlin/com/wire/android/ui/calling/CallState.kt
- app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallScreen.kt
- app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/calling/common/CallVideoPreview.kt
- app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
- app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
- app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModel.kt
- app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2025" title="AR-2025" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2025</a>  New Calls Mute the ongoing Call
</td></table>
<br />
----
----
PS: The fix is done on both sides, kalium and Reloaded
1. Incoming calls affect current call state: if you mute the incoming call, the current call will also be muted
2. call state in incoming call is not saved: if play with calling controls in the incoming call screen(mute, turn camera on) and accept the call you will not get last state of the call you have configured
we were calling muteCall method from AVS in incoming call screen
- make …
> fix: New calls mute the ongoing call(AR-2025)

- app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsState.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2121" title="AR-2121" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2121</a>  compose slider not syncing properly in user services screen
</td></table>
<br />
----
----
compose switch not syncing properly in conversation options screen
1. change the switch state immediately when clicked without waiting for dialog confirmation 
2. disable the switches when loading
https://drive.google.com/file/d/1aZUUPR38iFtbovrJboVMePnJUwooejkA/view?usp=sharing
----
----
----
1. E.g. …
> fix: AR-2121 compose slider not syncing properly in user services screen

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupState.kt
- app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
----
----
Don't show the protocol selection when creating a new conversation if MLS is disabled.
1. Enable MLS for your user in team settings
2. Tap create new conversation 
3. protocol selection is visible/hidden
----
----
----
> feat: hide the protocol selection when MLS is disabled 

- app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
----
----
When the user does the logout, we set the user-session as Invalid within the Reason that is SelfLogout, then based on the value of the Session, we redirect the user to the login page.
For other sessions like client-removed, user-deleted, and session-expired, we delete the session after showing the user a dialog and the reason. But for self-logout, since we don't show any dialogs after logout, the session will be there forever!
The session lived forever, and when the user opened the app, the user was redirected to the login page because the session still was there.
Clear the invalid-self-logout-session after redirecting the user to the login page.
_If there are some other pull requests related to this one (e.g. new releases of …
> fix(logout): delete invalid logout session after navigation

- app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
- app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
- app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1825" title="AR-1825" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1825</a>  1:1 calling - Take app to background and foreground again, video stays paused
</td></table>
<br />
----
----
Self video stays paused when moving the app into foreground in video call
We are not enabling the video again when the app return into foreground
Check if the app is back in the ongoing call screen and there is an established call then we turn on video
Start a call
Turn on your video
Put app in background
Return it into foreground from task manager
Video should be turned on again …
> fix(calling): Self video stays paused when moving the app into foreground in video call (AR-1825)

- app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
- app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
- app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
----
- [ x answers the question: _If merged, this PR will: ..._ ³
----
This PR updates the reference to Kalium submodule to be able to access the `removedBy` field needed to provide information on how a user left a group (voluntarily or removed by some other admin)
----
> feat: implement leave group

- app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
- app/src/main/kotlin/com/wire/android/util/FileUtil.kt
- app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1236" title="AR-1236" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />AR-1236</a>  Display notification for ongoing calls if the app is in the background
</td></table>
<br />
----
----
When killing the app, it will handle only the very first push notification.
If you re-open the app, Sync won't re-start and will stay disconnected.
While in the background, the app sets Kalium's ConnectionPolicy to `DISCONNECT_AFTER_PENDING_EVENTS`.
When coming to the foreground, the app sets it back to `KEEP_ALIVE`, but Kalium doesn't handle this upgrade.
1. When receiving a push notification, set the …
> fix: keep receiving notifications while in background (Related to AR-1236)

- app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
- app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2057" title="AR-2057" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2057</a>  Strange behavior on clicking Back button
</td></table>
<br />
----
----
When opening the app from the message notification and going back (by clicking on system back button or top bar back arrow button) the app closes instead of navigating to "home" screen.
The 1:1 conversation name is "Deleted User" briefly before the actual data is loaded.
When clicking on message notification and the app is closed, the app navigation stack is created from scratch and start screen is set to be "conversation" screen so …
> fix: back press after opening message notification and initial name [AR-2057]

- app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
- app/src/main/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManager.kt
- app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
- app/src/test/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManagerTest.kt
----
----
When the websocket drops due to unstable internet, and we receive a push notification, the app doesn't keep the connection even if it's in the foreground.
**The same can happen if we receive a push notification and manually open the app right afterwards.**
The `WireNotificationManager` is always upgrading the policy and then downgrading, without checking if the app is now in the foreground.
Delegate this responsibility to the `ConnectionPolicyManager`, which has a new function `handleConnectionOnPushNotification`:
- When a push notification is received, `handleConnectionOnPushNotification` is called.
- It will upgrade the policy, wait until live, and depending on criteria will downgrade the policy again or not.
If the user that …
> fix: connection policy being downgraded when app is in foreground

- app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/JoinButton.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
----
----
[AR-2008 - Join call button crashes if there is no given audio permission](https://wearezeta.atlassian.net/browse/AR-2008)
App crashed if trying to join an ongoing call through Join Call button in Home Screen (conversations list) and in Conversation list without have given audio permission.
There was no verification for audio permission.
Add audio permission verification in Join Call Button view component.
> chore: add join call button permission

- app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
- app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModel.kt
----
----
When starting a call and hanging up the call / ending the call in InitiatingCallScreen, it would invoke `navigateBack()` twice, then sometimes either closing the app completely or just crashing.
`navigateBack()` is being called both in `onClosedCall` listener and when clicking the `Hang Up` button.
Add a private variable to check if the hang up button was clicked, if so then we don't invoke `navigateBack()` again from `onClosedCall` listener, thus invoking it only once.
- Open App
- Start a call
- Before anyone answers the call, close/hang up/end the call through the button
- InitiatingCallScreen should be closed (only InitiatingCallScreen, nothing else)
> chore: double navigate back initiating call

- app/src/main/kotlin/com/wire/android/notification/WireFirebaseMessagingService.kt
- app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
- app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1812" title="AR-1812" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1812</a>  Memoryleak inside WireFirebaseMessagingService
</td></table>
<br />
----
----
WireFirebaseMessagingService is leaking instances.
When the service is destroyed, there may be some coroutines still working, collecting flows, etc.
Ideally, we should consume the `onMessageReceived` quickly and don't hold onto it for long. However we do process it for _some_ time.
With the current bug on Notifications, where we keep collecting ephemeral message notifications indeterminately, this memory leak becomes more …
> fix: memory leaking of WireFirebaseMessagingService (AR-1812)

- app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionState.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionsScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupState.kt
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
- app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2146" title="AR-2146" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />AR-2146</a>  Group Creation - Popup to signal offline therefore functionality is not available
</td></table>
<br />
----
----
- Given the phone is offline, or Given sync has failed, 
- When attempting to create a group conversation
- Then nothing happens, no feedback.
Handle the new result from the `CreateGroupConversationUseCase`, introduced in https://github.com/wireapp/kalium/pull/815
I also took a bit of time to re-organise the `GroupOptionsScreen.kt` into smaller Composable functions and removing …
> fix: handle lack of connectivity when creating group conversations (AR-2146)

- app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
- app/src/main/kotlin/com/wire/android/util/ui/StyledStringUtil.kt
- app/src/main/res/values/strings.xml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1195" title="AR-1195" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />AR-1195</a>  Display Other User’s connected devices
</td></table>
<br />
----
----
the design was not as the mocks in figma
updated the UI , to reflect the figma design
----
----
----
> fix: other user devices UI [AR-1195]

- app/src/main/kotlin/com/wire/android/ui/common/UserBadge.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/search/InternalContactSearchResultItem.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
- app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2178" title="AR-2178" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2178</a>  Guest, External etc labels not alligned
</td></table>
<br />
----
----
guest label was not aligned with the name in the search list 
we were passing fixed padding to the label 
make the user badge accept top padding argument so it we can pass different padding for different occurences 
----
----
----
> fix: guest label not aligned [AR-2178]

- app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
- app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileViewModelArrangement.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2190" title="AR-2190" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2190</a>  User Profiles are empty for unconnected Users
</td></table>
<br />
UserProfile is not loaded for not connected user and error is displayed
when the OtherUserProfile is opened app was trying to get ALL the necessary data and combine it into  a `state`
including: 
- `getOrCreateOneToOneConversation` which is needed only for connected users for BottomSheet menu
- `observeConversationRoleForUser` which is needed only for case when user came from the ConversationScreen, to display otherUser's role in that conversation.
And when user opens OtherUserProfile …
> fix: Empty UserProfile for not connected user (AR-2190)

- app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/MenuBottomSheetItem.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/search/InternalContactSearchResultItem.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/HomeSheetContent.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationTitle.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2088" title="AR-2088" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2088</a>  Texts in conversation context menu should use ellipsis
</td></table>
<br />
----
----
In some places texts were taking too much space resulting in making other items invisible: user membership badges on conversation list and user search list, notification type info and right arrow on conversation bottom sheet.
Add weights and proper spacings.
Look at conversations list (items with badges) and conversation notification settings row (it's visible on some device screens when you have German language set).
---- …
> fix: text ellipsis and spacing [AR-2088]

- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
----
----
the conversation screen state is updated from the io thread -> app crash
add `withContext(dispatsher.main())` 
----
----
----
> fix: conversation screen crash when user has no conversations

- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
- app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachment/AttachmentOptions.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2276" title="AR-2276" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2276</a>  If I am on a call, I can't open conversation menu(+ button)
</td></table>
<br />
`+` button on conversation doesn’t work if i am on a call
Conversation menu should take the same height as a keyboard, so user won't see any "jumping input" if he opens conversation menu when the keyboard is displayed.
We calculate the "accessible aria" size on each re-composition and compare it to the initial "accessible aria" (from the first composition) and if that `screenSize` is smaller than the initial we assume that the keyboard was opened and we can calculate its …
> fix: Can't open conversation menu during ongoing call (AR-2276)

- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2177" title="AR-2177" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2177</a>  + button on conv details doesn't expand after sending app background
</td></table>
<br />
When clicking on add + button, it expands the menu. If I send back to the background, open the app again but click the app icon (not recent apps), the button gets selected, but menu is not open
When app just returns from the background there is some moment when "available screen" space includes Android Navigation buttons space (and we remember that as a `fullScreenHeight`). So when re-composition is called it find out that the screen size is 24.dp smaller than …
> fix: Conversation options doesn't open after sending app to background (AR-2177)

- app/src/main/kotlin/com/wire/android/mapper/UICallParticipantMapper.kt
- app/src/main/kotlin/com/wire/android/ui/calling/ParticipantTile.kt
- app/src/main/kotlin/com/wire/android/ui/calling/common/CallingGridView.kt
- app/src/main/kotlin/com/wire/android/ui/calling/common/OneOnOneCallView.kt
- app/src/main/kotlin/com/wire/android/ui/calling/model/UICallParticipant.kt
- app/src/test/kotlin/com/wire/android/mapper/UICallParticipantMapperTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1234" title="AR-1234" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />AR-1234</a>  Screen sharing (receive)
</td></table>
<br />
----
----
This PR aims to display call participants screen share
Needs to be released with wireapp/kalium/pull/848
In a call request from others to share their screen
You should see their screen in the tiles
----
----
----
1. …
> feat: display screen sharing feed (AR-1234) 

- app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/SnackbarMessages.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/delete/DeleteMessageDialog.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/delete/DeleteMessageDialogHelper.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/delete/DeleteMessageDialogsState.kt
- app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewState.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1748" title="AR-1748" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1748</a>  [Images] Refactor Delete Message Functionality from gallery 
</td></table>
<br />
when use is trying to remove media message from the Gallery screen, app redirects him to the Conversation screen and shows the DeleteMessageDialog instead of showing that dialog in Gallery screen.
Also, all the tests in `MediaGalleryViewModelTest` were not running, because of wrong `@Test` import, it should be `org.junit.jupiter.api.Test`
it was implemented like this from the beginning
fix it
> fix: Delete message from gallery (AR-1748)

- app/src/main/kotlin/com/wire/android/util/LogFileWriter.kt
----
----
delete function was deleting the compressed files in the logs but not the current active file content
delete the active log file content
go to the debug screen and try to delete the logs and see if it's deleted or not 
----
----
----
> fix: delete log file

- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/HomeSheetContent.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2088" title="AR-2088" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2088</a>  Texts in conversation context menu should use ellipsis
</td></table>
<br />
----
----
The notification option value have wrong text color.
Change the text color to the right one.
Look at the notifications settings on the conversation settings bottom sheet.
----
----
> fix: notifications option text color on bottom sheet [AR-2088]

- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2279" title="AR-2279" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2279</a>  New Activity Section does not automatically appear without scrolling
</td></table>
<br />
----
----
When the user is on the conversation list, and a new message arrives, and “new activity” section should appear, then it’s hidden until the user scrolls up on the conversation list.
Turns out `Dp.Hairline` doesn't work for the `Spacer` and in practice it still makes the height equal to 0, then `LazyColumn` doesn't recognise it as an item (because it doesn't take any space).
Use `Divider` instead of `Spacer`, …
> fix: new activity section scroll issue #2 [AR-2279]
