- app/build.gradle.kts
- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/core/android.gradle.kts
- buildSrc/src/main/kotlin/scripts/compilation.gradle.kts
- buildSrc/src/main/kotlin/scripts/infrastructure.gradle.kts
- buildSrc/src/main/kotlin/scripts/quality.gradle.kts
- buildSrc/src/main/kotlin/scripts/variants.gradle.kts
This PR aims to refactor our ```gradle``` build system in order to organize it by functionality in a more modular way using Kotlin DSL pre-compiled scripts. 
Includes:
- Basic Build Variants Setup.
- Quality: which includes Lint Configuration.
- Compilation Options.
- Minor Refactor.
Everything has been extracted In order to keep the main ```build.gradle.kts``` file small and easy to understand.
> Refactor Build System with Kotlin DSL using pre-compiled scripts.

- app/build.gradle.kts
- buildSrc/src/main/kotlin/scripts/infrastructure.gradle.kts
- buildSrc/src/main/kotlin/scripts/variants.gradle.kts
Not much to say rather than a minor refactor to the build system in order to follow up best practices. 
In this case the code speaks by itself. :1234:
> Fix/refactor SourceSets and Infrastructure Script -  Gradle Kotlin DSL

- app/src/androidTest/kotlin/com/wire/android/FunctionalTest.kt
- app/src/androidTest/kotlin/com/wire/android/feature/auth/registration/CreateAccountActivityUITest.kt
- app/src/main/kotlin/com/wire/android/core/extension/Activity.kt
- app/src/main/kotlin/com/wire/android/core/extension/Fragment.kt
- app/src/main/kotlin/com/wire/android/feature/auth/registration/CreateAccountActivity.kt
- app/src/main/kotlin/com/wire/android/feature/auth/registration/CreateAccountFragment.kt
- app/src/main/kotlin/com/wire/android/feature/auth/registration/personal/CreatePersonalAccountFragment.kt
- app/src/main/kotlin/com/wire/android/feature/auth/registration/personal/CreatePersonalAccountViewPagerAdapter.kt
- app/src/main/kotlin/com/wire/android/feature/auth/registration/personal/email/CreatePersonalAccountEmailFragment.kt
- app/src/main/res/layout/activity_create_account.xml
- app/src/main/res/layout/fragment_create_personal_account.xml
- app/src/main/res/layout/fragment_create_personal_account_email.xml
- app/src/main/res/values-land/dimens.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles_tablayout.xml
- app/src/main/res/values/styles_textview.xml
- app/src/main/res/values/themes.xml
- app/src/test/kotlin/com/wire/android/AndroidTest.kt
- app/src/test/kotlin/com/wire/android/feature/auth/registration/personal/CreatePersonalAccountViewPagerAdapterTest.kt
- No Email/Phone entry fields for now
- Sets up TabLayout style
- Adds first unit test
> Registration #4: Add Create Account - Personal screen

- buildSrc/build.gradle.kts
The code speaks by itself. Only one line :smile:
> Change BuildSrc Dependencies object scope.

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
From 1.5.20
To 1.5.31
I was having issues when building a code with `inline` and `reified`. Updating Kotlin to `1.5.31` fixed for me.
> Refactor: Update Kotlin to 1.5.31

- app/src/main/kotlin/com/wire/android/feature/conversation/list/MainActivity.kt
- app/src/main/kotlin/com/wire/android/feature/sync/di/SyncModule.kt
- app/src/main/kotlin/com/wire/android/feature/sync/ui/SyncViewModel.kt
- app/src/test/kotlin/com/wire/android/feature/sync/ui/SyncViewModelTest.kt
In this PR, I am calling `listenToEventsUseCase` in `MainActivity `in order to start receiving messages.
> Start receiving messages

- app/src/main/kotlin/com/wire/android/core/events/EventRepository.kt
- app/src/main/kotlin/com/wire/android/core/events/datasource/EventDataSource.kt
- app/src/main/kotlin/com/wire/android/core/events/datasource/remote/NotificationRemoteDataSource.kt
- app/src/main/kotlin/com/wire/android/core/events/di/EventModule.kt
- app/src/test/kotlin/com/wire/android/core/events/datasource/EventDataSourceTest.kt
- app/src/test/kotlin/com/wire/android/core/events/usecase/ListenToEventsUseCaseTest.kt
This PR is pair programmed one between @vitorhugods and I.
It aims to improve the way we are emiting  events received from two different sources.
> [fix] Emitting events from different coroutines

- app/src/main/kotlin/com/wire/android/feature/conversation/content/domain/MessageEnvelopeCreator.kt
- app/src/test/kotlin/com/wire/android/feature/conversation/content/domain/MessageEnvelopeCreatorTest.kt
As discussed in #288, a dedicated envelope creator could be made so we have a specialised entity handling this.
I've took that and created a PR just for this for the reviewer's pleasure.
> Send messages: Part 13 - Create envelopes for sending messages

- .github/workflows/jira-lint-and-link.yml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQPIT-768" title="SQPIT-768" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />SQPIT-768</a>  Activate Jira Link Github workflow on all relevant client repositories
</td></table>
<br />
----
----
Pull Request should automatically be linked to JIRA when a JIRA issue number is present in the title
Use Wire's Jira Link workflow
N/A
----
----
----
1. E.g. `feature(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.
> ci: Add Jira Link workflow SQPIT-768

- .gitignore
- docker-agent/AndroidAgent
----
----
this pr adds the git library to the docker agent for later use on the build process
> chore(ci): added git library to docker agent setup

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- config/detekt/detekt.yml
- legacy/src/main/AndroidManifest.xml
----
----
Added Jetpack Compose lib to the project.
We'll need it in the project.
----
----
----
> feat: add Jetpack Compose libs to the project

- app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
- app/src/main/kotlin/com/wire/android/ui/theme/Theme.kt
- app/src/main/res/values/strings.xml
- buildSrc/src/main/kotlin/Dependencies.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-984" title="AR-984" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />AR-984</a>  Add version info in drawer
</td></table>
<br />
----
----
Added a Text view on the app drawer's bottom side with the app version name
> chore: add app version name to drawer [AR-984]

- app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
[Task-981](https://wearezeta.atlassian.net/browse/AR-981)
fixed the icon sizes in a drawer
> feat: Icon size in drawer

- app/src/main/kotlin/com/wire/android/ui/common/BottomNavigation.kt
- app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
[Task 983](https://wearezeta.atlassian.net/browse/AR-983)
----
> feat: Drawer color fix

- app/src/main/kotlin/com/wire/android/navigation/NavigationManager.kt
- app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
Fix for clearing the backStack on navigation
clearing backStack was not actually removing all the Composes and it's ViewModels.
> feat: Cleare backstack issue fix

- app/src/main/kotlin/com/wire/android/ui/common/FloatingActionButton.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
- app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
- app/src/main/res/values/strings.xml
[Task-997 ](https://wearezeta.atlassian.net/browse/AR-997)
----
----
- updated icon in FAB 
- updated text style in FAB
> feat: Fix fab styles

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
----
----
`coreLogic.getSessionScope` need `AuthSession` 
injecting current user session 
manual
----
----
> feat: injecting current session with hilt

- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/RowItem.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileScreen.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1133" title="AR-1133" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />AR-1133</a>  Conversation List Item missing ripple effect on click
</td></table>
<br />
----
----
Issue:
There was no ripple effect on RowItem click
Solution : 
Use combinedClickable to handle the ripple effect
----
> fix: no ripple effect on item click (AR-1133)

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDeviceViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileViewModel.kt
- app/src/main/kotlin/com/wire/android/util/CoreFailureUtil.kt
----
----
app not building
adapt the recent kalium changes to the app
----
----
----
> fix: app not building

- .github/workflows/gradle-run-tests.yml
----
----
Github actions builds a bit slow
Add ADV caching as recommended in https://github.com/ReactiveCircus/android-emulator-runner#usage
Checks are green
----
----
> ci: add adv caching

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileScreen.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileViewModel.kt
----
----
clicking logout the app only navigate to the login screen
call `LogoutUseCase`
----
----
----
> feat: actually logout when clicking logout

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/common/loading/CenteredCircularProgressBarIndicator.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsState.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsViewModel.kt
----
----
- Display all known contacts
----
----
----
> feat: display all known contacts 

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
----
----
https://github.com/wireapp/kalium/pull/370 changed they way we initialise CoreLogic in a breaking way.
Update root directory which we pass to CoreLogic.
App still runs.
----
----
----
> chore: update CoreLogic initialisation after refactoring

- app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
----
----
hard coded BE
replace STAGING with DEFAULT
----
----
> fix: hard coded STAGING BE for account creation

- app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
----
----
_fix the background color of the mesage list 
----
----
----
> fix: change the message list background color

- app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
- app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallState.kt
- app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
- app/src/test/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModelTest.kt
----
----
There is a UI and controls, but no tests
Tests for `IncomingCallViewModel` were implemented in this PR
This is the third and last PR for this epic.
> test: Update Calling UI - Part3

- app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
- app/src/test/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
----
----
develop branch build is failing
due to some kalium changes
fixed unit test
import the right class name
----
----
----
> fix: broken build 

- app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmail.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/EmptySearchQueryScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleScreen.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1545" title="AR-1545" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1545</a>  Url links don't work
</td></table>
<br />
----
----
Certain links were broken or not implemented. This PR fixes those, namely:
- The forgot password link
- The "learn more about user search" (link)[
----
----
----
> fix: fixed url links not working correctly [AR-1545]

- app/src/main/kotlin/com/wire/android/ui/settings/SettingsScreen.kt
- app/src/main/kotlin/com/wire/android/util/KaliumFileWriter.kt
----
----
change the log file type to .txt as .log was not able to be shared in wire
----
----
----
> chore: change log file type

- app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewState.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1599" title="AR-1599" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1599</a>  Create a personal account - First, Last names accept spaces
</td></table>
<br />
----
----
_If there are some other pull requests related …
> fix: validate blank fields in create account details [AR-1599]

- app/src/androidTest/java/com/wire/android/ui/RegisterDeviceTest.kt
- app/src/androidTest/java/com/wire/android/ui/RemoveDeviceScreenTest.kt
- app/src/androidTest/java/com/wire/android/ui/UserProfileScreenTest.kt
- app/src/androidTest/java/com/wire/android/utils/Extensions.kt
> test: fixed a flaky step

- app/build.gradle.kts
- app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/AppTopBarWithSearchBarLayout.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/SearchPeopleRouter.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleState.kt
- app/src/main/res/values/strings.xml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1662" title="AR-1662" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1662</a>  New Conversation - Back button after search brings back the search flow
</td></table>
<br />
----
----
Fix few bugs in the new conversation flow related to typos , and navigation .
(https://github.com/wireapp/kalium/pull/493)
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the …
> fix: new conversation bugs [AR-1662][AR-1402][AR-1454][AR-1408][AR-1530][AR-1473]

- app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
- app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
----
----
Fixes from the comments after the design review, adjustment on message behavior and animation https://wearezeta.atlassian.net/browse/AR-1415?focusedCommentId=101522
----
----
----
> fix: fixes from design review applied

- app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetLayout.kt
- app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallConversationItem.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallsScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationState.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/GeneralConversationItem.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionConversationItem.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationSheetContent.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
- app/src/main/kotlin/com/wire/android/util/ui/AssetImageFetcher.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1663" title="AR-1663" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1663</a>  Scrolling in the conversation is not smooth and images are flickering
</td></table>
<br />
----
----
while scrolling through the conversations and messages inside the conversation, it was slowly rendering
mapping was done on the UI thread
execute the mapping on default dispatcher
----
> fix: slow list rendering by execute mapping on default dispatcher (AR-1663)

- app/src/main/res/values/strings.xml
> fix:  typo in the search screen

- app/src/main/kotlin/com/wire/android/media/CallRinger.kt
- app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
- app/src/test/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModelTest.kt
----
----
Rejecting an incoming call crashes the app
We are stopping app ringing when rejecting the call, the Media manager at that time is not initialized or it is released.
Surround stopping ringing with` try catch`
----
----
----
1. E.g. …
> fix: crash after rejecting an incoming call

- app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
> fix: multiple notifications

- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/GeneralConversationItem.kt
- app/src/main/res/values/strings.xml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1403" title="AR-1403" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1403</a>  Group conversations look weird without a name
</td></table>
<br />
----
----
_If there are some other pull requests related to this one …
> feat: display unnamed conversation when the group conversation has no name (AR-1403)

- app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
> feat: display the team name coming out of get user details use case result

- .github/workflows/generate-changelog.yml
- .github/workflows/gradle-run-ui-tests.yml
- .github/workflows/gradle-run-unit-tests.yml
- .github/workflows/semantic-commit-lint.yml
----
----
Some GitHub Actions have newer versions an can be upgraded
Update:
- checkout@v3
- setup-java@v3
- cache@v3
- upload-artifact@v3
- download-artifact@v3
----
----
> chore: update github actions

- app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
----
----
unresolved reference after updating kalium in AR
----
----
----
> fix: unresolved reference

- app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleScreen.kt
- app/src/main/res/values/strings.xml
> fix: show more instead of show all on contact button

- app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1855" title="AR-1855" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />AR-1855</a>  Hide convo list search bar for P1
</td></table>
<br />
----
----
The Search Bar in conversation list is half baked, giving testers a bad experience.
Regrettably hide it for now and enable it once conversation filtering is properly implemented.
----
----
----
> chore: hide conversation list search bar AR-1855

- app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleState.kt
----
----
It is not used anywhere a left over from a refactor 
----
----
----
1. …
> fix: remove scroll position from the view model

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallViewModel.kt
- app/src/test/kotlin/com/wire/android/ui/calling/OngoingCallViewModelTest.kt
----
----
There was some changes in Kalium that will break AR.
UseCase name change. (from `GetOngoingCallUseCase` to `ObserveEstablishedCallsUseCase`)
Adjust code using correct class `ObserveEstablishedCallsUseCase`
> chore: adjust usecase name change

- app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1883" title="AR-1883" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />AR-1883</a>  Hide new account button in self profile screen
</td></table>
<br />
----
----
While we do support account creation while logged in, we don't currently support multiple accounts in the UI.
Hide the new account button in self profile for the moment
Manual
Open your own user's profile, check that the new account button doesn't appear.
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most …
> chore: hide new account button in self profile AR-1883

- app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
- app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1553" title="AR-1553" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />AR-1553</a>  Adapt current user search to support federated search (UI)
</td></table>
<br />
----
----
This is follow up PR with tests because previous one had conflicts with kalium so we decided to merge things separately to not block others
_If there are some other pull requests …
> test: (AR-1553) Federated search

- app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
> fix: adjust the message padding according to designs

- app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
----
----
Just for making navigation looks much more smoother
Start or receive a new call
https://user-images.githubusercontent.com/18124919/176866333-57045bee-4656-4122-9955-71e9ec637e0a.mp4
----
----
----
> feat(calling): adding transition animation for incoming and outgoing screens

- app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
> fix: thread on assigning inner search people state

- app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/AppTopBarWithSearchBarLayout.kt
- app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/SearchBarState.kt
- app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/SearchPeopleRouter.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1857" title="AR-1857" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1857</a>  On New Conversations screen - Take App to background or Lock device, app Crashes
</td></table>
<br />
----
----
- When app was taken to the background on new conversation screen there was a crash 
-Due because LazyListState is not Serializable, when rememberSaveable was called on SearchState it was causing a crash
- Do not save the LazyList 
- Provide the lambda wrapper instead to save function …
> fix: app crashing on background when on new conversation screen [AR-1857][AR-1983]

- README.md
- scripts/tail_logcat_to_file.sh
----
----
- Updates Kalium ref to have the changes and fixes for big accounts, fetch conversation details by batch of 200
- Add logcat helper to being able to see more than the IDE supports, rotates the log file on exit
----
----
----
> chore: update kalium ref and bash script helper for logcat

- app/src/main/kotlin/com/wire/android/di/AppModule.kt
- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
- app/src/main/kotlin/com/wire/android/di/LogWriterModule.kt
> refactor: unify provide prefix for @Provides annotated methods

- app/src/main/kotlin/com/wire/android/ui/theme/ThemeUtils.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1948" title="AR-1948" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />AR-1948</a>  'Light mode' in the app by default
</td></table>
<br />
----
----
Dark mode is not yet fully supported so we shouldn't allow it in the app until we handle it properly.
Disabled the dark theme for all theme-dependent items (currently only color scheme is theme-dependent).
Open the app having the dark theme set on the device to see that it supports only light theme.
----
----
----
1. E.g. …
> chore: disable dark mode [AR-1948]

- app/src/main/kotlin/com/wire/android/WireApplication.kt
- app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreenViewModel.kt
----
----
Update after API breakage in the KaliumLogger
----
----
----
> chore: update after KaliumLogger API breakage

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModel.kt
- app/src/test/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModelTest.kt
----
----
This PR is to handle the changes from Kalium when storing the calls in the database.
Tests were done in code and also with @dogaguclu
> chore: adjust store calls to database

- app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleViewModel.kt
> fix: pass qualified id when navigating to other user profile screen

- app/src/main/res/values/strings.xml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1869" title="AR-1869" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />AR-1869</a>  [Login] Wrong copy on "already logged in" dialog
</td></table>
<br />
----
----
[AR-1869]
update the copy
----
[AR-1869]: https://wearezeta.atlassian.net/browse/AR-1869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update copy in account already logged in dialog [AR-1869]

- app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
- app/src/main/kotlin/com/wire/android/ui/common/LegalHoldIndicator.kt
- app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
- app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypesPreview.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
- app/src/main/kotlin/com/wire/android/util/StringUtil.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1465" title="AR-1465" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />AR-1465</a>  Navigate to other user’s profile from the conversation with them
</td></table>
<br />
----
----
User needs to be able to navigate to self or other profile by clicking on user's avatar on conversation screen.
Implemented clickable avatar navigating to the self or other profile, added some small visual updates to the other profile screen.
Open conversation and click on the avatar that's next to the message.
https://user-images.githubusercontent.com/30429749/180040337-120dde3e-7aaf-4c40-979f-cf5e1b64c1eb.mp4 …
> feat: clickable message avatars [AR-1465]

- app/src/main/kotlin/com/wire/android/ui/common/CollapsingTopBarScaffold.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserConnectionStatusInfo.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2073" title="AR-2073" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2073</a>  Crash - Go details of a guest user over participants list
</td></table>
<br />
----
----
app crashing when we press on the details tap in the user profile that we don't have connection with due to undefined pager
define an empty pager with no screens just to handle the tap clicks  …
> fix: guest details crash [AR-2073]

- app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1831" title="AR-1831" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1831</a>  [Conversation view] Message text has wrong font size
</td></table>
<br />
----
----
-Fix the missaligned style of the body with the design specs …
> fix: adjust the message body style to match design specs (AR-1831)

- app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationSheetState.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
- app/src/main/res/values/strings.xml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-1791" title="AR-1791" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-1791</a>  1:1 Conversation disappears after other user deletes their account
</td></table>
<br />
----
----
Currently, we are ignoring or not showing conversations with deleted users, now with this PR we have the same behavior as other clients, showing "default" for this deleted users
----
----
----
> fix: conversations with deleted users (AR-1791)

- app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
----
----
[AR-1892 - No sound is played when receiving incoming call with app in background](https://wearezeta.atlassian.net/browse/AR-1892)
When app was in background and you receive an incoming call notification, no ringing sound was played.
Ringing sound was only implemented in incoming call screen and not in the notification itself.
Add ringing sound in the notification.
- Open App
- Wait for Sync to complete (should wait at least 6 seconds)
- Put App in background
- Receive incoming call
- Notification with sound will be displayed and sound will be played
> chore: add sound to incoming call notifications

- app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
- app/src/main/kotlin/com/wire/android/util/FileUtil.kt
----
----
Samsung Note cannot load PDFs from the app
1. Incorrect flags when creating the file open Intent.
2. missing file extension in the asset path.
1. replace or with addFlag
2. just add the file extension
manual 
receive pdf -> click open -> choose Samsung Note -> Allet jut
----
----
----
> fix: some PDF files readers are not able to load pdfs from the app

- .github/workflows/gradle-run-ui-tests.yml
- .github/workflows/gradle-run-unit-tests.yml
- app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
- app/src/main/kotlin/com/wire/android/notification/Models.kt
- app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
- app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
- app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2039" title="AR-2039" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />AR-2039</a>  Admin deletes a group conversation that I belong to
</td></table>
<br />
----
----
This PR adds the notification handling when a group-conversation is deleted by it's creator.
Needs releases with: https://github.com/wireapp/kalium/pull/763
https://user-images.githubusercontent.com/5806454/183061379-7c0c3423-4240-492b-8d69-9a356674860a.mov
----
----
----
1. E.g. `feat(conversation-list): Sort conversations …
> feat: delete conversations notification (AR-2039)

- app/src/main/kotlin/com/wire/android/ui/calling/common/CallerDetails.kt
- app/src/main/kotlin/com/wire/android/ui/common/spacers/Height.kt
- app/src/main/kotlin/com/wire/android/ui/common/spacers/HorizontalSpace.kt
- app/src/main/kotlin/com/wire/android/ui/common/spacers/VerticalSpace.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
- app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/ACOL-12" title="ACOL-12" target="_blank"><img alt="Topic" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />ACOL-12</a>  Extract Spacers to more readable composables
</td></table>
<br />
----
----
_If there are some other pull requests related to this one …
> chore: spacer proposal (ACOL-12)

- buildSrc/src/main/kotlin/Dependencies.kt
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
----
----
Upgrade Gradle to `7.5.1`.
Includes Kalium reference update so Kalium also uses the same wrapper version.
- https://github.com/wireapp/kalium/pull/796
----
----
> chore: upgrade gradle wrapper

- app/build.gradle.kts
- app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsState.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupScreen.kt
- app/src/main/res/values/strings.xml
- buildSrc/src/main/kotlin/Dependencies.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2157" title="AR-2157" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />AR-2157</a>  [AR] Protocol and Cyphersuite indication in the Group properties
</td></table>
<br />
----
----
Exposed protocol info in the Group Details screen.
Needs to be merged with Kalium.
https://github.com/wireapp/kalium/pull/808
Create an mls group, in the group details you should be able to see the protocol info.
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most …
> feat(mls-conversation): show protocol info in conversation details (AR-2157)

- app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2163" title="AR-2163" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />AR-2163</a>  Expose debug option to lower key material update period
</td></table>
<br />
----
----
Add the lowerKeyingMaterialsThreshold config value to the kalium configFile,
Needed in kalium.
Release with Kalium PR.
https://github.com/wireapp/kalium/pull/812
Create an MLS conversation, then go to the conversation details, remember the keying material update value, close the app and open it after one minute. after the sync check the group details again the keying materials update value should be …
> feat(mls-conversation): add lowerKeyingMaterialsThreshold to kaliumConfig file (AR-2163)

- app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
- app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
- app/src/test/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModelTest.kt
----
----
Update kalium reference
----
> fix(kalium-ref): update kalium reference

- app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/usecase/ObserveParticipantsForConversationUseCase.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2175" title="AR-2175" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2175</a>  Bots/services should not be admins in group convos
</td></table>
<br />
----
----
Services now showing as admins in the participant's list 
filter the admins list by memebership 
----
----
----
> fix: separate service from admins [AR-2175]

- app/src/main/kotlin/com/wire/android/WireApplication.kt
- app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
- app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/FolderHeader.kt
- app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupScreen.kt
- buildSrc/src/main/kotlin/FeatureConfigs.kt
- default.json
…conversationsdetails
----
----
* Make all title for grouping UPPERCASE
* Fix detecting private build to show mls features for play-test builds
* To match the designs
* To enable features for debug purposes
No needed new tests.
For QA: in play-test builds should be able to see all the details of the mls group
----
----
----
> fix(conversation): detect private build and uppercase titles in group details

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/feature/SwitchCurrentAccountUseCase.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileState.kt
- app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
- app/src/main/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManager.kt
- app/src/main/res/values/strings.xml
----
----
user need to be able to switch between multiple authenticated accounts
updating the ConnectionPolicyManager to observe the current session and update the sync policy whenever the current session is changed
----
----
----
> feat: account switching

- app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
- app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreen.kt
- app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreenViewModel.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2297" title="AR-2297" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />AR-2297</a>  Add an entry in debug menu, which shows the current client ID
</td></table>
<br />
----
----
current client ID need to be displayed in the debug screen
just add it
navigate to the debug screen and the current client ID should be displayed
----
----
----
> feat: add an entry in debug menu which shows the current client [AR-2297]

- app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/AR-2328" title="AR-2328" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />AR-2328</a>  SSO Login broken after redirect from Okta login page
</td></table>
<br />
----
----
Deeplink for SSO login was not handled, because isServerConfigOnPremises was returning true before this check
Moved isServerConfigOnPremises lower in checklist
_Specify …
> fix: moved isServerConfigOnPremises lower to handle other deeplinks (AR-2328)
